-- AlterTable
ALTER TABLE "CompanyAdmin" ADD COLUMN     "canDelete" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "canEdit" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "canViews" BOOLEAN NOT NULL DEFAULT true;
