name: Deploy to VPS

on:
  push:
    branches:
      - main # Triggers on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Promodz
            
            # 1. Sync code
            git config --global --add safe.directory /var/www/Promodz
            git fetch origin main
            git reset --hard origin/main
            
            # 2. Update Backend
            cd promodz_backend
            npm install
            
            # 3. FIX PERMISSIONS (The missing piece)
            # This makes the prisma file executable for the deployment process
            chmod +x node_modules/.bin/prisma
            
            # 4. Sync Database & Generate Client
            npx prisma generate
            npx prisma db push --accept-data-loss # Use db push for faster dev updates
            
            # 5. Restart with new environment/code
            pm2 restart api-backend --update-env
            
            # 6. Update Frontend
            cd ../Frontend
            npm install
            npm run build